name: Bug Report
description: Report a bug or unexpected behavior
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out the form below.

  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of the bug
      placeholder: What happened?
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Configure multiarch-config.yaml with...
        2. Run workflow with...
        3. See error...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: The build should complete successfully
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: The build failed with error...
    validations:
      required: true

  - type: textarea
    id: config
    attributes:
      label: Configuration
      description: Your multiarch-config.yaml (sanitized if needed)
      render: yaml
      placeholder: |
        package_name: example
        github_repo: owner/repo
        ...
    validations:
      required: false

  - type: textarea
    id: logs
    attributes:
      label: Relevant Logs
      description: Any relevant error messages or logs
      render: shell
      placeholder: Paste relevant logs here
    validations:
      required: false

  - type: input
    id: version
    attributes:
      label: Action Version
      description: Which version of the action are you using?
      placeholder: e.g., v1.0.0, main
    validations:
      required: true

  - type: input
    id: runner
    attributes:
      label: Runner Environment
      description: Where is the action running?
      placeholder: e.g., ubuntu-latest, self-hosted
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context about the problem
      placeholder: Add any other context here
    validations:
      required: false
