blank_issues_enabled: false
contact_links:
  - name: GitHub Discussions
    url: https://github.com/ranjithrajv/debian-multiarch-builder/discussions
    about: Ask questions and discuss ideas with the community
  - name: Documentation
    url: https://github.com/ranjithrajv/debian-multiarch-builder/tree/main/docs
    about: Browse the documentation for guides and troubleshooting
