# Example configuration demonstrating distribution-specific architecture support
# - i386: only supported in Debian Bookworm (deprecated in Trixie+)
# - armel: supported in Bookworm and Trixie (last release, removed in Forky+)
package_name: example-package
github_repo: owner/repository
artifact_format: tar.gz

# Debian distributions to build for
debian_distributions:
  - bookworm
  - trixie
  - forky
  - sid

# Architecture mappings
# {version} will be replaced with the actual version number
architectures:
  amd64:
    release_pattern: "example_{version}_x86_64.tar.gz"

  arm64:
    release_pattern: "example_{version}_aarch64.tar.gz"

  armel:
    release_pattern: "example_{version}_arm.tar.gz"

  i386:
    release_pattern: "example_{version}_i686.tar.gz"

# Specify which architectures are supported for specific distributions
distribution_arch_overrides:
  # i386 is only supported in Bookworm (v12), deprecated in Trixie (v13+)
  i386:
    distributions:
      - bookworm

  # armel is supported in Bookworm and Trixie (last release), removed in Forky (v14+)
  armel:
    distributions:
      - bookworm
      - trixie

# Optional: If binary is in a subdirectory after extraction
# binary_path: ""
