# Multi-architecture configuration for eza
package_name: eza
github_repo: eza-community/eza
artifact_format: tar.gz

# Debian distributions to build for
debian_distributions:
  - bookworm
  - trixie
  - forky
  - sid

# Architecture mappings
# {version} will be replaced with the actual version number (e.g., v0.18.0)
architectures:
  amd64:
    release_pattern: "eza_x86_64-unknown-linux-musl.tar.gz"

  arm64:
    release_pattern: "eza_aarch64-unknown-linux-gnu.tar.gz"

  armhf:
    release_pattern: "eza_arm-unknown-linux-gnueabihf.tar.gz"

  # Add more architectures as they become available upstream

# Optional: Specify which architectures are supported for specific distributions
# distribution_arch_overrides:
#   riscv64:
#     distributions:
#       - trixie
#       - forky
#       - sid

# Optional: If binary is in a subdirectory after extraction
# For eza, the binary might be directly in the root of the tarball
# binary_path: ""
