# Multi-architecture configuration for uv
package_name: uv
github_repo: astral-sh/uv
artifact_format: tar.gz

# Debian distributions to build for
debian_distributions:
  - bookworm
  - trixie
  - forky
  - sid

# Auto-discovery mode: Simply list architectures
# Release patterns are automatically discovered from GitHub releases
architectures:
  - amd64
  - arm64
  - armel
  - armhf
  - ppc64el
  - s390x
  - riscv64

# Specify which architectures are supported for specific distributions
distribution_arch_overrides:
  # riscv64 is only supported in Trixie (v13) and later, not in Bookworm (v12)
  riscv64:
    distributions:
      - trixie
      - forky
      - sid

  # armel is supported in Bookworm and Trixie only (last release)
  armel:
    distributions:
      - bookworm
      - trixie
