# Multi-architecture configuration for uv
package_name: uv
github_repo: astral-sh/uv
artifact_format: tar.gz

# Debian distributions to build for
debian_distributions:
  - bookworm
  - trixie
  - forky
  - sid

# Auto-discovery mode: Simply list architectures
# Release patterns are automatically discovered from GitHub releases
architectures:
  - amd64
  - arm64
  - armel
  - armhf
  - ppc64el
  - s390x
  - riscv64

# Distribution-specific architecture support is handled automatically by the action
# Built-in rules:
#   - i386: Bookworm only (deprecated in Trixie+)
#   - armel: Bookworm only (last version as regular architecture)
#   - riscv64: Trixie+ only (introduced in Trixie)
# You can override these with distribution_arch_overrides if needed
